### ISSUE TITLE
build failed when doing carthage command (exit code:65)

### ISSUE THREAD

**Issue by ledikari** [ReSwift/CounterExample#10]
using the command carthage update --platform iOS --no-use-binaries yields error.

carthage version
0.22.0

xcodebuild -version
Xcode 8.3.2
Build version 8E2002

Here is the error message
 
Build Failed
	Task failed with exit code 65:

/usr/bin/xcrun xcodebuild -project /Users/ledikari/Workspace/CounterExample/Carthage/Checkouts/ReSwift/ReSwift.xcodeproj -scheme ReSwift-iOS -configuration Release -derivedDataPath /Users/ledikari/Library/Caches/org.carthage.CarthageKit/DerivedData/ReSwift/2.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0v/jjz1fhbn6qg22z8lbg5l41mh0000gn/T/carthage-xcodebuild.b3eiNu.log

**Comment by sunshinejr** [comment]
Hey @ledikari, thanks for raising an issue. I've just merged a PR with updating dependencies & API (#9) , can you try if you still have the same problem?

**Comment by ledikari** [comment]
hey thanks, no problems now :)

**Comment by sunshinejr** [comment]
Nice to hear! Thank you for your time :)

**Comment by KGDhingra** [comment]
I am facing same issue please help
