### ISSUE TITLE
Update to Xcode 8 / Swift 3

### ISSUE THREAD

**Issue by ashfurrow** [ReSwift/CounterExample#5]
I'm interested in taking this on, will report back later on progress.

**Comment by ColinEberhardt** [comment]
fixed via #6

**Comment by ashfurrow** [comment]
Rats, was going to work on this for a conference workshop...

**Comment by ColinEberhardt** [comment]
Sorry @ashfurrow - I'm sure you can find other project that require a similar upgrade ;-)

**Comment by ashfurrow** [comment]
No worries! I'm keen to introduce the attendees to ReSwift. Any other chores or anything that needs doing?

**Comment by ColinEberhardt** [comment]
> Any other chores or anything that needs doing?

I'm not really a 'core' member of ReSwift, so am probably not the best person to ask regarding what needs doing! I was planning on writing an article on ReSwift for Ray Wendlich's website, and while learning the framework spotted a need for this super-simple example, so contributed it back.

I did however, find a number of aspects of ReSwift that confused me somewhat - see the details here:

https://github.com/ReSwift/ReSwift/issues/150

Good luck with the workshop!
